//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cheapdscin.ResourceFile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cheapdscin.ResourceFile.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheap DSC is currently serving all over India serving all pin code in India..
        /// </summary>
        public static string AboutUs_ContentLine1 {
            get {
                return ResourceManager.GetString("AboutUs_ContentLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheap DSC &quot;An Award Winning Company&quot; is a licensed Registration Authority under Information Technology Act 2000 of India for issuance of Digital Signature Certificates in India. Cheap DSC is a leading PKI Solutions provider, Digital Signature Certificates, eSign Services, Document Signer Certificate, Code Signing Certificates, Signing Certificates, Encryption Certificates. We are a Chennai based Company established in 2017 with presence on PAN India Basis with 50+ partners. With in a short span of time we a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutUs_ContentLine2 {
            get {
                return ResourceManager.GetString("AboutUs_ContentLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first step is determining which Cheap DSC relationship best aligns with your company&apos;s products, services, expertise and business goals. Cheap DSC programs are available to help you resell our product related to Digital Signature Certificates, FIPS Certified USB Token and many more..
        /// </summary>
        public static string AboutUs_ContentLine3 {
            get {
                return ResourceManager.GetString("AboutUs_ContentLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheap DSC believes that partnership and the resulting synergies are the cornerstone of any successful business. Building mutually advantageous relationships that allow sustained business expansion and customer loyalty defines the broad scope of our Partner Program..
        /// </summary>
        public static string AboutUs_ContentLine4 {
            get {
                return ResourceManager.GetString("AboutUs_ContentLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-Solutions offers PKI Solutions like Digital Signature Certificates, eSign Services, Document Signer Certificate, Code Signing Certificates, Signing Certificates, Encryption Certificates..
        /// </summary>
        public static string AboutUs_Statement1 {
            get {
                return ResourceManager.GetString("AboutUs_Statement1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheap DSC was established in 2017 in Chennai to serve Digital Signature Certificates to various clients..
        /// </summary>
        public static string AboutUs_Statement2 {
            get {
                return ResourceManager.GetString("AboutUs_Statement2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To help customers in transact securly over the web with his/her unique identify..
        /// </summary>
        public static string AboutUs_Statement3 {
            get {
                return ResourceManager.GetString("AboutUs_Statement3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leading change, Integrity, Respect for the individual, Excellence, Learning and sharing..
        /// </summary>
        public static string AboutUs_Statement4 {
            get {
                return ResourceManager.GetString("AboutUs_Statement4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognized &amp; Licensed Registration Authority ( RA) Under e-Mudhra Limited.
        /// </summary>
        public static string AboutUs_Statement5 {
            get {
                return ResourceManager.GetString("AboutUs_Statement5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5+ Years of Experience | Recognized RA | 70 + Associates | 50k+ DSC ISSUED | Team of Professionals.
        /// </summary>
        public static string AboutUs_Statement6 {
            get {
                return ResourceManager.GetString("AboutUs_Statement6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Place to get all digital Signature Product at cheap price with best service in India..
        /// </summary>
        public static string AboutUs_SubTitle {
            get {
                return ResourceManager.GetString("AboutUs_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs_Title {
            get {
                return ResourceManager.GetString("AboutUs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What we Offer.
        /// </summary>
        public static string AboutUs_What_we_Offer {
            get {
                return ResourceManager.GetString("AboutUs_What we Offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All India.
        /// </summary>
        public static string All_India {
            get {
                return ResourceManager.GetString("All India", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Name.
        /// </summary>
        public static string Business_Name {
            get {
                return ResourceManager.GetString("Business Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certifications.
        /// </summary>
        public static string Certifications {
            get {
                return ResourceManager.GetString("Certifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheap Dsc.
        /// </summary>
        public static string Cheap_Dsc {
            get {
                return ResourceManager.GetString("Cheap Dsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Count.
        /// </summary>
        public static string ClientCount {
            get {
                return ResourceManager.GetString("ClientCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Over India.
        /// </summary>
        public static string Footer_AllOverIndia {
            get {
                return ResourceManager.GetString("Footer_AllOverIndia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Footer_ContactUs {
            get {
                return ResourceManager.GetString("Footer_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2021 cheapdsc.com Designed &amp; Developed by.
        /// </summary>
        public static string Footer_CopyRights {
            get {
                return ResourceManager.GetString("Footer_CopyRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Stop Place for All Digital Signature Certificate, DGFT, Usb Token at cheap price with best service..
        /// </summary>
        public static string Footer_Description {
            get {
                return ResourceManager.GetString("Footer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Us on Above Social Media Platform.
        /// </summary>
        public static string Footer_FollowUsOnSocial {
            get {
                return ResourceManager.GetString("Footer_FollowUsOnSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Reach Us.
        /// </summary>
        public static string Footer_HowToReachUs {
            get {
                return ResourceManager.GetString("Footer_HowToReachUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string Footer_PrivacyPolicy {
            get {
                return ResourceManager.GetString("Footer_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowest Price.
        /// </summary>
        public static string LowestPrice {
            get {
                return ResourceManager.GetString("LowestPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string Menu_AboutUs {
            get {
                return ResourceManager.GetString("Menu_AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class 3.
        /// </summary>
        public static string Menu_Class3 {
            get {
                return ResourceManager.GetString("Menu_Class3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo.
        /// </summary>
        public static string Menu_Combo {
            get {
                return ResourceManager.GetString("Menu_Combo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo With Usb Token.
        /// </summary>
        public static string Menu_ComboWithUsbToken {
            get {
                return ResourceManager.GetString("Menu_ComboWithUsbToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Menu_ContactUs {
            get {
                return ResourceManager.GetString("Menu_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DGFT Certificate.
        /// </summary>
        public static string Menu_DGFTCertificate {
            get {
                return ResourceManager.GetString("Menu_DGFTCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DGFT With Usb Token.
        /// </summary>
        public static string Menu_DGFTWithUsbToken {
            get {
                return ResourceManager.GetString("Menu_DGFTWithUsbToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption.
        /// </summary>
        public static string Menu_Encryption {
            get {
                return ResourceManager.GetString("Menu_Encryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption With Usb Token.
        /// </summary>
        public static string Menu_EncryptionWithUsbToken {
            get {
                return ResourceManager.GetString("Menu_EncryptionWithUsbToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Menu_Home {
            get {
                return ResourceManager.GetString("Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import &amp; Export.
        /// </summary>
        public static string Menu_ImportAndExport {
            get {
                return ResourceManager.GetString("Menu_ImportAndExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual.
        /// </summary>
        public static string Menu_Individual {
            get {
                return ResourceManager.GetString("Menu_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation.
        /// </summary>
        public static string Menu_Organisation {
            get {
                return ResourceManager.GetString("Menu_Organisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Menu_Product {
            get {
                return ResourceManager.GetString("Menu_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicing Areas.
        /// </summary>
        public static string Menu_ServicingAreas {
            get {
                return ResourceManager.GetString("Menu_ServicingAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        public static string Menu_Signature {
            get {
                return ResourceManager.GetString("Menu_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature With Usb Token.
        /// </summary>
        public static string Menu_SignatureWithToken {
            get {
                return ResourceManager.GetString("Menu_SignatureWithToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usb Token.
        /// </summary>
        public static string Menu_UsbToken {
            get {
                return ResourceManager.GetString("Menu_UsbToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission.
        /// </summary>
        public static string Mission {
            get {
                return ResourceManager.GetString("Mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Cmp.
        /// </summary>
        public static string Parent_Cmp {
            get {
                return ResourceManager.GetString("Parent Cmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewals.
        /// </summary>
        public static string Renewals {
            get {
                return ResourceManager.GetString("Renewals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicing Area.
        /// </summary>
        public static string Servicing_Area {
            get {
                return ResourceManager.GetString("Servicing Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        public static string Values {
            get {
                return ResourceManager.GetString("Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHY Cheap DSC.
        /// </summary>
        public static string WHY_Cheap_DSC {
            get {
                return ResourceManager.GetString("WHY Cheap DSC", resourceCulture);
            }
        }
    }
}
