//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cheapdscin.ResourceFile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cheapdscin.ResourceFile.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Over India.
        /// </summary>
        public static string Footer_AllOverIndia {
            get {
                return ResourceManager.GetString("Footer_AllOverIndia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Footer_ContactUs {
            get {
                return ResourceManager.GetString("Footer_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2021 cheapdsc.com Designed &amp; Developed by.
        /// </summary>
        public static string Footer_CopyRights {
            get {
                return ResourceManager.GetString("Footer_CopyRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Stop Place for All Digital Signature Certificate, DGFT, Usb Token at cheap price with best service..
        /// </summary>
        public static string Footer_Description {
            get {
                return ResourceManager.GetString("Footer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Us on Above Social Media Platform.
        /// </summary>
        public static string Footer_FollowUsOnSocial {
            get {
                return ResourceManager.GetString("Footer_FollowUsOnSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Reach Us.
        /// </summary>
        public static string Footer_HowToReachUs {
            get {
                return ResourceManager.GetString("Footer_HowToReachUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string Footer_PrivacyPolicy {
            get {
                return ResourceManager.GetString("Footer_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string Menu_AboutUs {
            get {
                return ResourceManager.GetString("Menu_AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class 3.
        /// </summary>
        public static string Menu_Class3 {
            get {
                return ResourceManager.GetString("Menu_Class3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo.
        /// </summary>
        public static string Menu_Combo {
            get {
                return ResourceManager.GetString("Menu_Combo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo With Usb Token.
        /// </summary>
        public static string Menu_ComboWithUsbToken {
            get {
                return ResourceManager.GetString("Menu_ComboWithUsbToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Menu_ContactUs {
            get {
                return ResourceManager.GetString("Menu_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DGFT Certificate.
        /// </summary>
        public static string Menu_DGFTCertificate {
            get {
                return ResourceManager.GetString("Menu_DGFTCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DGFT With Usb Token.
        /// </summary>
        public static string Menu_DGFTWithUsbToken {
            get {
                return ResourceManager.GetString("Menu_DGFTWithUsbToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption.
        /// </summary>
        public static string Menu_Encryption {
            get {
                return ResourceManager.GetString("Menu_Encryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption With Usb Token.
        /// </summary>
        public static string Menu_EncryptionWithUsbToken {
            get {
                return ResourceManager.GetString("Menu_EncryptionWithUsbToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Menu_Home {
            get {
                return ResourceManager.GetString("Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import &amp; Export.
        /// </summary>
        public static string Menu_ImportAndExport {
            get {
                return ResourceManager.GetString("Menu_ImportAndExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual.
        /// </summary>
        public static string Menu_Individual {
            get {
                return ResourceManager.GetString("Menu_Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation.
        /// </summary>
        public static string Menu_Organisation {
            get {
                return ResourceManager.GetString("Menu_Organisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Menu_Product {
            get {
                return ResourceManager.GetString("Menu_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicing Areas.
        /// </summary>
        public static string Menu_ServicingAreas {
            get {
                return ResourceManager.GetString("Menu_ServicingAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        public static string Menu_Signature {
            get {
                return ResourceManager.GetString("Menu_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature With Usb Token.
        /// </summary>
        public static string Menu_SignatureWithToken {
            get {
                return ResourceManager.GetString("Menu_SignatureWithToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usb Token.
        /// </summary>
        public static string Menu_UsbToken {
            get {
                return ResourceManager.GetString("Menu_UsbToken", resourceCulture);
            }
        }
    }
}
